# -*- coding: utf-8 -*-
"""Agente Smolagents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H7C9XC0LQHfwZbEJpVcb39vQWeqX337E

# **CREACIÓN DE UN AGENTE BÁSICO DE IA CON SMOLAGENTS**

En este ejercicio construiremos un agente de inteligencia artificial funcional desde cero. Aprenderás a configurar el modelo base, definir herramientas personalizadas y permitir que el agente razone, actúe y observe sus resultados de forma autónoma. El objetivo es comprender la estructura fundamental de un agente y cómo combinar lógica, herramientas y lenguaje natural en un flujo integrado.

# Instalamos librerías
Instalamos las librerías que proporcionan sus componentes principales.
Instalaremos SmolAgents (framework para crear agentes de IA), DuckDuckGo Search y ddgs (para realizar búsquedas web), huggingface_hub (para conectarse con modelos alojados en Hugging Face), además de utilidades comunes como pytz, pyyaml y requests para manejo de zonas horarias, lectura de archivos YAML y peticiones HTTP:
"""

# --- Instalar dependencias necesarias (ejecuta esta celda primero) ---
!pip install -q smolagents duckduckgo-search ddgs huggingface_hub pytz pyyaml requests

# Instalación de dependencias necesarias:
# smolagents: framework para crear agentes basados en LLM y ciclo ReAct
# duckduckgo-search / ddgs: librerías para realizar búsquedas web
# huggingface_hub: conexión con modelos y herramientas del Hugging Face Hub
# pytz: manejo de zonas horarias (usado en la tool de hora)
# pyyaml: lectura de archivos YAML (usado internamente por smolagents con load_tool e InferenceClientModel)
# requests: peticiones HTTP (para APIs y descargas del Hub)

"""# Importaciones
Este bloque importa las librerías básicas del agente, os para el token, componentes de smolagents para crear y ampliar el agente, y datetime junto con pytz para manejar fechas y zonas horarias.
"""

import os
# 1) Pega tu token con scope "read"
os.environ["HF_TOKEN"] = ""   # <-- tu token

# --- Importaciones necesarias ---
from smolagents import CodeAgent, DuckDuckGoSearchTool, InferenceClientModel, load_tool, tool
import datetime, pytz

# Librerías principales de Smolagents:
# CodeAgent: ejecuta el ciclo ReAct (pensar–actuar–observar)
# DuckDuckGoSearchTool: permite búsquedas web como acción del agente
# InferenceClientModel: conecta con modelos alojados en Hugging Face (LLM)
# load_tool: carga herramientas externas desde el Hub de Hugging Face
# tool: decorador para convertir funciones Python en herramientas del agente

"""# Herramientas personalizadas
En esta sección se definen herramientas propias que amplían las capacidades del agente y no forman parte de la librería Smolagents.
respuesta_final formatea la salida final del modelo, mientras que obtener_hora_zona_horaria permite consultar la hora local en una zona horaria determinada.
Ambas funciones se registran como tools mediante el decorador @tool, lo que permite que el agente las invoque automáticamente durante su ciclo de razonamiento y acción.
"""

# 'respuesta_final' se usa para devolver la salida final del agente al usuario.
# Permite que el agente formatee correctamente su conclusión después del ciclo de pensamiento-acción-observación.

from smolagents import tool
@tool
def respuesta_final(respuesta: str) -> str:
    """Returns the final answer to the user."""
    return f"Respuesta final: {respuesta}"

# 'obtener_hora_zona_horaria' es una herramienta funcional que permite al agente
# consultar información del entorno, en este caso la hora local según una zona horaria.

@tool
def obtener_hora_zona_horaria(zona_horaria: str) -> str:

    try:
        tz = pytz.timezone(zona_horaria) # cargo la zona horaria con pytz
        hora_local = datetime.datetime.now(tz).strftime("%Y-%m-%d %H:%M:%S") # obtiene la hora y la formatea como texto
        return f"La hora local actual en {zona_horaria} es: {hora_local}" # Devuelve la hora
    except Exception as e:
        return f"Error al obtener la hora para '{zona_horaria}': {str(e)}"

"""# Configuración del modelo
Este bloque configura el modelo de lenguaje que usará el agente.
Se conecta al modelo Qwen/Qwen2.5-Coder-7B-Instruct alojado en Hugging Face, utilizando el token almacenado en las variables de entorno.
Los parámetros max_tokens y temperature controlan la longitud y la creatividad de las respuestas generadas.
"""

# --- Configuración del modelo (proveedor público) ---
modelo = InferenceClientModel(
    model_id="Qwen/Qwen2.5-Coder-7B-Instruct", # La librería gestiona automáticamente la conexión con el endpoint
    token=os.environ["HF_TOKEN"], # Token de autenticación para acceder a la API de Hugging Face
    max_tokens=1024, # Longitud de la respuesta máxima, sobre 700 palabras
    temperature=0.5, # Control de aleatoriedad: 0 = preciso, 1 = creativo
)

"""# Herramientas del agente (Ciclo REACT: ACT)
Las herramientas definen las **acciones concretas** que el agente puede ejecutar para interactuar con su entorno.
Cada herramienta es una **función Python** (propia o integrada) que el agente invoca cuando, durante su razonamiento,
decide que necesita realizar una acción externa: buscar información, consultar una API, calcular un valor o generar una imagen.

En este ejemplo, el agente usa herramientas integradas de *Smolagents* —como la búsqueda web y la generación de imágenes—
que amplían sus capacidades sin necesidad de programarlas desde cero.  
Todas las herramientas se incluyen en una lista al crear el agente, y este las selecciona dinámicamente en cada
iteración del ciclo **ReAct** según lo que necesite hacer.

En resumen: las herramientas son el **puente entre el pensamiento del modelo y las acciones reales** que ejecuta en el mundo.
"""

# --- Herramientas del agente ---
busqueda = DuckDuckGoSearchTool()

# Tool de imagen desde el Hugginface (opcional). Si falla, la omitimos.
try:
    generador_imagen = load_tool("agents-course/text-to-image", trust_remote_code=True)
except Exception as e:
    print(f"Nota: no se cargó la tool de imagen ({e}). Continuamos sin ella.")
    generador_imagen = None

# LLamo a las herramientas que voy a usar
tools = [respuesta_final, obtener_hora_zona_horaria, busqueda]

# Compruebo generador
if generador_imagen is not None:
    tools.append(generador_imagen)

# --- Crear el agente ---
agente = CodeAgent(
    model=modelo, # THINK (modelo que razona)
    tools=tools, # ACT (acciones tools)
    max_steps=6, # Número máximo de ciclos de razonamiento
    verbosity_level=0, # 1 es más verboso, aparece más información por pantalla
)

"""# Ejecutamos"""

# EJECUTAMOS CICLO REACT
# --- Pruebas de funcionamiento ---
prompt1 = "Busca quién fue Alan Turing y explica por qué es importante en la historia de la inteligencia artificial, en español."
prompt2 = "Consulta qué hora es actualmente en 'America/New_York' y compárala con la de 'Europe/Madrid', en español."
prompt3 = """
Genera una imagen de un gato en alta resolución y fotorealista.
Devuelve solo el bloque de código Python, con cada instrucción en una línea separada:

image = image_generator("Una imagen de un gato en alta resolución y fotorealista.")
final_answer(image)
"""
print(agente.run(prompt1))
# print(agente.run(prompt2))
#print(agente.run(prompt3))